version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless         
  pre_build:
    commands:
      - npm install --silent --no-progress
  build:
    commands:
      - mkdir -p target/dev
      - mkdir -p target/prod
      - serverless package --package target/dev --stage dev -v -r eu-west-1
      - serverless package --package target/prod --stage prod -v -r eu-west-1
artifacts:
    files: 
    - target/**/*
    - resources/*
    - serverless.yml
    - buildspec-dev.yml
    - buildspec-prod.yml
    - deploy.sh